-- 기존 테이블 삭제 (데이터 날아감 주의!)
DROP TABLE IF EXISTS posts;

-- Unified Schema (Excel + Agent)
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    
    -- 식별자
    url TEXT UNIQUE NOT NULL,        -- tweet_url -> url (Excel 통일)
    
    -- 내용
    content TEXT,                    -- tweet_content -> content (Excel 통일)
    
    -- 시간
    time_str TEXT,                   -- posted_time -> time_str (Excel 통일, KST/String)
    time TEXT,                       -- time (Excel 통일, US Numeric/String)
    
    -- 분석 결과
    impact_on_market TEXT,           -- act_on_market -> impact_on_market (이름 개선)
    sentiment_score FLOAT,
    market_impact_score FLOAT,
    keywords TEXT,
    sector TEXT,
    reason TEXT
);

-- RLS 설정
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for all users" ON posts FOR ALL USING (true) WITH CHECK (true);
